table:
  name: files
  schema: storage
configuration:
  column_config:
    bucket_id:
      custom_name: bucketId
    created_at:
      custom_name: createdAt
    etag:
      custom_name: etag
    id:
      custom_name: id
    is_uploaded:
      custom_name: isUploaded
    metadata:
      custom_name: metadata
    mime_type:
      custom_name: mimeType
    name:
      custom_name: name
    size:
      custom_name: size
    updated_at:
      custom_name: updatedAt
    uploaded_by_user_id:
      custom_name: uploadedByUserId
  custom_column_names:
    bucket_id: bucketId
    created_at: createdAt
    etag: etag
    id: id
    is_uploaded: isUploaded
    metadata: metadata
    mime_type: mimeType
    name: name
    size: size
    updated_at: updatedAt
    uploaded_by_user_id: uploadedByUserId
  custom_name: files
  custom_root_fields:
    delete: deleteFiles
    delete_by_pk: deleteFile
    insert: insertFiles
    insert_one: insertFile
    select: files
    select_aggregate: filesAggregate
    select_by_pk: file
    update: updateFiles
    update_by_pk: updateFile
object_relationships:
  - name: bucket
    using:
      foreign_key_constraint_on: bucket_id
  - name: department_file
    using:
      foreign_key_constraint_on:
        column: file_id
        table:
          name: department_files
          schema: public
insert_permissions:
  - role: user
    permission:
      check:
        bucket_id:
          _in:
            - profile_pics
            - default
      set:
        uploaded_by_user_id: x-hasura-User-Id
      columns:
        - is_uploaded
        - size
        - metadata
        - bucket_id
        - etag
        - mime_type
        - name
        - created_at
        - updated_at
        - id
        - uploaded_by_user_id
    comment: ""
select_permissions:
  - role: public
    permission:
      columns:
        - is_uploaded
        - size
        - metadata
        - bucket_id
        - etag
        - mime_type
        - name
        - created_at
        - updated_at
        - id
        - uploaded_by_user_id
      filter:
        bucket_id:
          _eq: profile_pics
    comment: ""
  - role: user
    permission:
      columns:
        - is_uploaded
        - size
        - metadata
        - bucket_id
        - etag
        - mime_type
        - name
        - created_at
        - updated_at
        - id
        - uploaded_by_user_id
      filter:
        _or:
          - uploaded_by_user_id:
              _eq: X-Hasura-User-Id
          - department_file:
              department:
                id:
                  _in: X-Hasura-departments
          - bucket_id:
              _eq: profile_pics
    comment: ""
delete_permissions:
  - role: user
    permission:
      filter:
        _or:
          - uploaded_by_user_id:
              _eq: X-Hasura-User-Id
          - department_file:
              department:
                id:
                  _in: X-Hasura-Departments
    comment: ""
event_triggers:
  - name: graphite_files_events
    definition:
      delete:
        columns: '*'
        payload: '*'
      enable_manual: false
      insert:
        columns: '*'
        payload: '*'
      update:
        columns: '*'
        payload: '*'
    retry_conf:
      interval_sec: 30
      num_retries: 3
      timeout_sec: 30
    webhook: http://ai:8090/v1/webhooks/storage-files
    headers:
      - name: X-Graphite-Webhook-Secret
        value_from_env: GRAPHITE_WEBHOOK_SECRET
    cleanup_config:
      batch_size: 10000
      clean_invocation_logs: true
      clear_older_than: 168
      paused: false
      schedule: 0 0 * * *
      timeout: 60
